{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "portfolio.fullname" . }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- if .Values.backend.enabled }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "portfolio.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
          {{- end }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "portfolio.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
{{- end }}
